- .gitignore
> Added: .gitignore

- build.sbt
- project/ProjectInfo.scala
- project/build.properties
- project/plugins.sbt
> Added: Project config files

- build.sbt
> Added: Set to use LoggerF

- src/main/scala/githubpages/GitHubPagesKeys.scala
Added: sbt setting and task keys
> Added: sbt setting and task keys

- src/main/scala/githubpages/GitHubPagesKeys.scala
> Added: More sbt `SettingKey`s

- src/main/scala/githubpages/GitHubPagesKeys.scala
Really minor change in String formatting
> Really minor change in String formatting

- src/main/scala/loggerf/sbt/SbtLogger.scala
> Added: SbtLogger for logger-f

- src/main/scala/filef/FileError.scala
- src/main/scala/filef/FileF.scala
Added: utility for file handling
> Added: utility for file handling

- src/main/scala/errors/StackTraceToString.scala
Added: util to convert `StackTrace` to String
> Added: util to convert StackTrace to String

- .github/workflows/build.yml
- .github/workflows/sbt-build-simple.sh
- src/main/scala/filef/FileError.scala
- src/main/scala/filef/FileF.scala
- src/main/scala/loggerf/sbt/SbtLogger.scala
> Added: GitHub Actions

- src/main/scala/effectie/cats/Attempt.scala
- src/main/scala/effectie/cats/Attemptable.scala
> Added: Attempt

- src/main/scala/effectie/cats/Attempt.scala
- src/main/scala/effectie/cats/Attemptable.scala
> Improved: Attemptable

- src/main/scala/filef/FileError.scala
- src/main/scala/filef/FileF.scala
Added: FileF.relativePathOf to find relative path of the file in the given base directory.
> Added: FileF.relativePathOf to find relative path

- src/main/scala/githubpages/github/Data.scala
- src/main/scala/githubpages/github/GitHubApi.scala
- src/main/scala/githubpages/github/GitHubError.scala
Added: GitHub API to commit and push
* GitHub API to commit and push a certain directory and any files and dirs in it to a specific branch in a GitHub repo.
In `sbt-github-pages` case, it's commit and push a directory to the `gh-pages` branch in the given GitHub repo.
> Added: GitHub API to commit and push

- build.sbt
- src/main/scala/githubpages/github/GitHubApi.scala
* Effectie: 0.4.0 => 1.0.0
* logger-f: 0.2.0 => 0.3.1
> Upgraded: Effectie and logger-f

- src/main/scala/githubpages/github/Data.scala
- src/main/scala/githubpages/github/GitHubApi.scala
* `IsBlob` is actually a function to check if the give file is a text file.
> Changed: IsBlob to IsText

- src/main/scala/githubpages/GitHubPagesKeys.scala
- src/main/scala/githubpages/GitHubPagesPlugin.scala
Added: `GitHubPagesPlugin` to publish `gh-pages`
> Added: GitHubPagesPlugin to publish gh-pages

- src/main/scala/githubpages/GitHubPagesPlugin.scala
> Fixed: Log messages

- project/build.properties
Upgraded: sbt 1.3.10 => 1.3.12
> Upgraded: sbt 1.3.10 => 1.3.12

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-simple.sh
- build.sbt
Added: GitHub Actions to release to GitHub and publish to Bintray
> Added: GitHub Actions to release to GitHub and publish to Bintray

- README.md
Added: `README.md` - how to use
> Added: README.md - how to use

- README.md
Updated: `README.md` - added link to the doc site.
> Updated: README.md - added link to the doc site

- website/docs/config.md
Updated: Docs with more config info
> Updated: Docs with more config info

- website/docs/config.md
Updated: Docs - removed: unnecessary info in setting key
> Updated: Docs - removed: unnecessary info in setting key

- website/docs/getting-started.md
- website/docs/run.md
> Updated: Docs

- website/docs/config.md
Updated: Docs - restructured the config page
> Updated: Docs - restructured the config page

- src/main/scala/githubpages/github/GitHubApi.scala
Close #36 - Change accepted text config
> Close #36 - Change accepted text config

- build.sbt
- project/plugins.sbt
- website/docs/config.md
- website/docs/getting-started.md
Updated: Docs in accordance with the changes in v0.1.1
> Updated: Docs in accordance with the changes in v0.1.1

- website/docs/run.md
Fixed: incorrect info in `run.md`
> Fixed: incorrect info in run.md

- .github/workflows/make-docusaurus.yml
- .github/workflows/publish-github-pages.yml
- build.sbt
- project/plugins.sbt
Use `sbt-docusaur` to build and publish Docusaurus website.
> Use sbt-docusaur to build and publish Docusaurus website.

- website/docusaurus.config.js
Added: The GitHub link to the top havbar.
> Added: The GitHub link to the top havbar.

- .github/workflows/make-docusaurus.yml
- .github/workflows/publish-github-pages.yml
Changed: GitHub Actions config - with Java/Scala params + Node.js upgrade 14.2.0 => 14.4.0
> Changed: GitHub Actions config

- website/docusaurus.config.js
- website/static/CNAME
> Added: CNAME

- src/main/scala/githubpages/GitHubPagesPlugin.scala
Fix #49 - publishToGitHubPages does not report error when it fails
> Fix #49 - publishToGitHubPages does not report error when it fails

- src/main/scala/githubpages/GitHubPagesPlugin.scala
- src/main/scala/githubpages/github/GitHubApi.scala
Fix #51 - Error when there is any directory with no file
> Fix #51 - Error when there is any directory with no file

- website/src/css/custom.css
Changed: The max width of the container - 1140px => 1240px
> Changed: The max width of the container

- src/main/scala/githubpages/GitHubPagesPlugin.scala
Close #59 - Some failed cases of `publishToGitHubPages` task should fail properly
> Close #59 - Some failed cases of publishToGitHubPages task should fail properly

- .github/workflows/build.yml
- .github/workflows/make-docusaurus.yml
- .github/workflows/publish-github-pages.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-simple.sh
Changed: Scala version in CI config
> Changed: Scala version in CI config

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-simple.sh
- project/build.properties
> Changed: sbt 1.3.12 => 1.3.13

- build.sbt
- src/main/scala/filef/FileF.scala
- src/main/scala/githubpages/GitHubPagesPlugin.scala
- src/main/scala/githubpages/github/GitHubApi.scala
* Cats 2.1.1 => 2.2.0
* Cats Effect 2.1.3 => 2.2.0
> Upgraded: Cats and Cats Effect

- build.sbt
- project/plugins.sbt
- src/main/scala/githubpages/GitHubPagesPlugin.scala
- src/main/scala/githubpages/github/GitHubApi.scala
* Changed: Scala and sbt versions
* Scala `2.12.11` => `2.12.12`
* sbt `1.3.12` => `1.3.13`
* Upgraded: libraries and sbt plugins
* Hedgehog `bd4e0cc785915e0af20d2a7ead5267d49b1de7b1` => `0.5.1`
* github4s `0.24.0` => `0.25.0`
* http4s `0.21.3` => `0.21.6`
* effectie `1.0.0` => `1.3.0`
* logger-f `0.4.0` => `1.3.1`
> Changed: Scala and sbt versions / Upgraded: libraries and sbt plugins

- src/main/scala/githubpages/GitHubPagesKeys.scala
- src/main/scala/githubpages/GitHubPagesPlugin.scala
- src/main/scala/githubpages/github/Data.scala
- src/main/scala/githubpages/github/GitHubApi.scala
Close #56 - Support GitHub Enterprise
> Close #56 - Support GitHub Enterprise

- build.sbt
- src/main/scala/githubpages/GitHubPagesPlugin.scala
Close #68 - Environment variables for GitHub Enterprise config
> Close #68 - Environment variables for GitHub Enterprise config

- project/plugins.sbt
- website/docs/config.md
- website/docs/examples.md
- website/docs/getting-started.md
* Updated: docs for `v0.2.0` - GitHub Enterprise support
* Upgraded: `sbt-docusaur` `0.1.4` => `0.2.0`
> Publish docs

- .github/workflows/publish-github-pages.yml
- project/plugins.sbt
- website/docusaurus.config.js
Upgraded: sbt-docusaur 0.1.4 => 0.2.1 with proper config
> Upgraded: sbt-docusaur 0.1.4 => 0.2.1 with proper config

- .github/workflows/make-docusaurus.yml
> Fixed: make-docusaurus.yml

- src/main/scala/githubpages/github/GitHubApi.scala
Close #74 - A single commit to publish GitHub Pages
> Close #74 - A single commit to publish GitHub Pages

- build.sbt
Added: `pluginCrossBuild / sbtVersion`
> Added: pluginCrossBuild / sbtVersion

- project/build.properties
> Upgraded: sbt 1.3.13 => 1.4.1

- project/build.properties
> Upgraded: sbt 1.4.1 => 1.4.6

- build.sbt
Upgraded: Hedgehog 0.5.1 => 0.6.1
> Upgraded: Hedgehog 0.5.1 => 0.6.1

- build.sbt
- src/main/scala/filef/FileF.scala
Upgraded: libraries
* cats-core: `2.2.0` => `2.3.1`
* cats-effect: `2.2.0` => `2.3.1`
* github4s: `0.25.0` => `0.27.1`
* http4s: `0.21.6` => `0.21.15`
* effectie-cats-effect: `1.3.0` => `1.8.0`
* logger-f: `1.3.1` => `1.7.0`
* kind-projector: `0.11.0` => `0.11.3`
> Upgraded: libraries

- src/main/scala/githubpages/github/GitHubApi.scala
Added: a comment of the reference to GitHub API abuse rate limit
> Added: a comment of the reference to GitHub API abuse rate limit

- .github/workflows/build.yml
- .github/workflows/make-docusaurus.yml
- .github/workflows/publish-github-pages.yml
- .github/workflows/release.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
Close #85 - Upgrade libraries and sbt
* sbt-devoops 1.0.3 => 2.0.0 - Changed: GitHub Actions config accordingly
* Cats 2.3.1 => 2.4.2
* Cats Effect 2.3.1 =. 2.3.3
* github4s 0.27.1 => 0.28.2
* http4s 0.21.15 => 0.21.19
> Close #85 - Upgrade libraries and sbt

- project/plugins.sbt
- website/docs/examples.md
- website/docs/getting-started.md
Updated: docs - also upgraded `sbt-docusaur`: `0.3.0` => `0.4.0`
> Updated: docs - also upgraded sbt-docusaur 0.3.0 => 0.4.0

- .scalafmt.conf
- build.sbt
- project/build.properties
- project/plugins.sbt
Updated: config / Upgraded: libraries, sbt and plugin
> Updated: config / Upgraded: libraries, sbt and plugin

- .github/workflows/build.yml
- .github/workflows/make-docusaurus.yml
- .github/workflows/manual-publish-github-pages.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-simple.sh
Updated: GitHub Actions config
> Updated: GitHub Actions config

- build.sbt
- project/ProjectInfo.scala
> Clean up - build.sbt

- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
Close #96 - Publish directly to Maven Central
> Close #96 - Publish directly to Maven Central

- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- project/ProjectInfo.scala
- project/plugins.sbt
- website/package-lock.json
- website/package.json
> Upgraded: Docusaurus

- README.md
- website/docs/examples.md
- website/docs/getting-started.md
Updated: docs - with new version info
> Updated: docs - with new version info

- .github/workflows/build.yml
- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- .github/workflows/release.yml
- website/docs/examples.md
> Updated: docs - example

- website/docs/examples.md
- website/docs/getting-started.md
Updated: docs with the new release info
> Updated: docs with the new release info

- project/plugins.sbt
Upgraded sbt plugins
- sbt-devoops `2.3.0` => `2.6.0`
- sbt-docusaur `0.5.0` => `0.6.0`
> Upgraded sbt plugins

- src/main/scala/filef/FileF.scala
- src/main/scala/githubpages/GitHubPagesPlugin.scala
- src/main/scala/githubpages/github/GitHubApi.scala
Issue #106 - Updated code in accordance with the changes in the new libs
> Issue #106 - Updated code in accordance with the changes in the new libs

- build.sbt
Clean up and reformatting `build.sbt`
> Clean up and reformatting build.sbt

- website/docs/examples.md
- website/docs/getting-started.md
Updated: The docs with the new version info
> Updated: The docs with the new version info

- src/main/scala/githubpages/GitHubPagesPlugin.scala
- src/main/scala/githubpages/github/GitHubApi.scala
- src/main/scala/githubpages/github/GitHubError.scala
Close #114 - Add a link to the doc site to explain how to create publish branch
> Close #114 - Add a link to the doc site to explain how to create publish branch

- .scalafmt.conf
- src/main/scala/githubpages/GitHubPagesPlugin.scala
Updated: `.scalafmt.conf` and re-formatted
> Updated: .scalafmt.conf and re-formatted

- website/docs/examples.md
- website/docs/getting-started.md
Updated: docs - with the new version (0.8.0) info
> Updated: docs - with the new version (0.8.0) info

- src/main/scala/githubpages/github/GitHubApi.scala
Fix #119 - `publishToGitHubPages` fails if you have greater than 30 branches alphabetically before `gh-pages`
There might be a better way, but for now, this fixes the issue. I probably need to think about using another GitHub API client that I've been developing (so slowly).
> Fix #119 - `publishToGitHubPages` fails if you have greater than 30 branches alphabetically before `gh-pages`

- project/plugins.sbt
Upgraded: sbt-docusaur `0.7.0` => `0.8.1` / sbt-devoops `2.10.0` => `2.14.0`
> Upgraded: sbt-docusaur 0.7.0 => 0.8.1 / sbt-devoops 2.10.0 => 2.14.0

- project/build.properties
Upgrade: sbt `1.5.1` => `1.5.8`
> Upgrade: sbt 1.5.1 => 1.5.8

- .github/pr-labeler.yml
- .github/workflows/pr-labeler.yml
Add: PR Labeler - GitHub Actions
> Add: PR Labeler - GitHub Actions

- build.sbt
- project/plugins.sbt
Close #131 - Publish to `s01.oss.sonatype.org` (the new Maven central)
> Close #131 - Publish to s01.oss.sonatype.org (the new Maven central)

- .scalafmt.conf
- src/main/scala/errors/StackTraceToString.scala
- src/main/scala/filef/FileError.scala
- src/main/scala/filef/FileF.scala
- src/main/scala/githubpages/GitHubPagesKeys.scala
- src/main/scala/githubpages/GitHubPagesPlugin.scala
- src/main/scala/githubpages/github/Data.scala
- src/main/scala/githubpages/github/GitHubApi.scala
- src/main/scala/githubpages/github/GitHubError.scala
Update: `.scalafmt.conf` and reformat
> Update: .scalafmt.conf and reformat

- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- project/plugins.sbt
- website/docusaurus.config.js
Upgrade sbt plugins - sbt-docusaur `0.8.1` => `0.9.0` to solve newly added `appId` config property
- Also upgrade Node version in GitHub Actions from `14.4.0` => `14.16.0`
- sbt-devoops `2.14.0` => `2.16.0`
> Upgrade sbt plugins - sbt-docusaur 0.8.1 => 0.9.0 to solve newly added appId config property

- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
Upgrade Docusaurus `2.0.0-alpha.74` => `2.0.0-beta.14`
> Upgrade Docusaurus 2.0.0-alpha.74 => 2.0.0-beta.14

- src/main/scala/githubpages/GitHubPagesKeys.scala
- src/main/scala/githubpages/GitHubPagesPlugin.scala
Close #165 - Add `settingKey` to set the request timeout for publishing GitHub Pages
> Close #165 - Add settingKey to set the request timeout for publishing GitHub Pages

- website/docs/examples.md
- website/docs/getting-started.md
Update: docs with the latest `sbt-github-pages` - `0.8.1` => `0.10.0`
> Update: docs with the latest sbt-github-pages - 0.8.1 => 0.10.0

- project/plugins.sbt
Upgrade: sbt-docusaur `0.10.0` => `0.12.0`
> Upgrade: sbt-docusaur 0.10.0 => 0.12.0

- .scalafmt.conf
- build.sbt
- src/main/scala/filef/FileError.scala
- src/main/scala/githubpages/GitHubPagesKeys.scala
- src/main/scala/githubpages/GitHubPagesPlugin.scala
- src/main/scala/githubpages/github/Data.scala
- src/main/scala/githubpages/github/GitHubApi.scala
- src/main/scala/githubpages/github/GitHubError.scala
Close #180 - Upgrade effectie and logger-f to 2.0.0-beta4, and update the code accordingly / also upgrade other libraries
- effectie 2.0.0-beta2 => 2.0.0-beta4
- logger-f 2.0.0-beta2 => 2.0.0-beta4
- global sbt version 1.2.8 => 1.6.2
- hedgehog 0.9.0 => 0.10.1
- cats 2.8.0 => 2.9.0
- cats-effect 3.3.14 => 3.4.3
- http4s blaze client 0.23.12 => 0.23.13
- extras 0.20.0 => 0.26.0
> Close #180 - Upgrade effectie and logger-f to 2.0.0-beta4, and update the code accordingly / also upgrade other libraries

- build.sbt
`build.sbt` - camelCase to PascalCase in version names
> `build.sbt` - camelCase to PascalCase in version names

- src/main/scala/filef/FileF.scala
Update to use Scala'3 import `_` syntax
> Update to use Scala'3 import _ syntax

- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- website/package-lock.json
- website/package.json
Bump Docusaurus `2.0.0-beta.14` => `2.0.1`
> Bump Docusaurus `2.0.0-beta.14` => `2.0.1`

- project/plugins.sbt
> Bump sbt-docusaur to 0.15.0

- website/docs/examples.md
- website/docs/getting-started.md
Update: docs - with the latest version info
> Update: docs - with the latest version info

- project/plugins.sbt
- src/main/scala/githubpages/github/GitHubApi.scala
Close #216 - Add `sbt-devoops-starter`
> Close #216 - Add `sbt-devoops-starter`

- project/plugins.sbt
Close #218 - Bump `sbt-devoops` to `3.1.0`
> Close #218 - Bump `sbt-devoops` to `3.1.0`

- project/plugins.sbt
- website/docs/examples.md
- website/docs/getting-started.md
Update docs and bump sbt-docusaur
* Update docs: the new version info
* Bump sbt-docusaur to 0.16.0
> Update docs and bump sbt-docusaur

- website/docs/config.md
Update docs: Fix missing closing triple backticks
> Update docs: Fix missing closing triple backticks

- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
> Bump Docusaurus to 3.1.1

- project/plugins.sbt
> Bump sbt-docusaur to 0.17.0
