kevin-lee/sbt-github-pages

src/main/scala/filef/FileError.scala

Fixed: missing file param for `FileNotFound` construction in `fromNonFatal` - file has been removed.

Fixed: missing file param for FileNotFound construction in fromNonFatal

---

changelogs/0.1.0.md

* Added: `GitHubPagesPlugin` to publish `gh-pages` (#18)
* [All PRs](https://github.com/Kevin-Lee/sbt-github-pages/issues?utf8=%E2%9C%93&q=is%3Aclosed+milestone%3Amilestone1)

sbt-github-pages v0.1.0

---

README.md
changelogs/0.1.1.md
project/ProjectInfo.scala

* Replace `master` branch with `main` branch (#25)
* Change accepted text config (#36)

sbt-github-pages v0.1.1

---

project/plugins.sbt

Removed: The repo for `sbt-docusaur` from `plugin.sbt` since it's now available in the official sbt plugin repo

Removed: The repo for sbt-docusaur from plugin.sbt

---

changelogs/0.1.2.md
project/ProjectInfo.scala

* `publishToGitHubPages` does not report error when it fails (#49)
* Error when there is any directory with no file in it (#51)

sbt-github-pages v0.1.2

---

changelogs/0.1.3.md
project/ProjectInfo.scala

* Some failed cases of `publishToGitHubPages` task should fail properly (#59)

sbt-github-pages v0.1.3

---

changelogs/0.2.0.md
project/ProjectInfo.scala

* Support GitHub Enterprise (#56)
```scala
gitHubPagesGitHubBaseUrl: SettingKey[String]
gitHubPagesGitHubAuthorizeUrl: SettingKey[String]
gitHubPagesGitHubAccessTokenUrl: SettingKey[String]
gitHubPagesGitHubHeaders: SettingKey[Map[String, String]]
```
* Environment variables for GitHub Enterprise config (#68)
* `GITHUB_ENT_BASE_URL` for `gitHubPagesGitHubBaseUrl`
* `GITHUB_ENT_AUTHORIZE_URL` for  `gitHubPagesGitHubAuthorizeUrl`
* `GITHUB_ENT_ACCESS_TOKEN_URL` for `gitHubPagesGitHubAccessTokenUrl`
* `GITHUB_ENT_HEADERS` for `gitHubPagesGitHubHeaders`

sbt-github-pages v0.2.0

---

changelogs/0.3.0.md
project/ProjectInfo.scala

* A single commit to publish GitHub Pages (#74)

sbt-github-pages v0.3.0

---

changelogs/0.4.0.md
project/ProjectInfo.scala

* Upgrade libraries and sbt (#85)
* sbt-devoops `1.0.3` => `2.0.0` - Changed: GitHub Actions config accordingly
* Cats `2.3.1` => `2.4.2`
* Cats Effect `2.3.1` => `2.3.3`
* github4s `0.27.1` => `0.28.2`
* http4s `0.21.15` => `0.21.19`

sbt-github-pages v0.4.0

---

.github/workflows/manual-publish-github-pages.yml

Changed: publishing GitHub pages is now manual

Changed: publishing GitHub pages is now manual

---

.github/workflows/manual-publish-github-pages.yml

Updated: `manual-publish-github-pages.yml` - The condition to ignore the `gh-pages` branch for building the doc site.

Updated: manual-publish-github-pages.yml

---

.github/workflows/build.yml
.github/workflows/sbt-build-simple.sh
build.sbt
project/build.properties
project/plugins.sbt

Close #93 - Upgrade sbt plugin and libraries
* sbt `1.4.9` => `1.5.1`
* sbt-devoops `2.1.0` => `2.3.0`
* http4s `0.21.20` => `0.21.22`
* cats-core `2.4.2` => `2.6.0`
* cats-effect `2.3.3` => `2.5.0`
* github4s `0.28.2` => `0.28.4`
* effectie `1.9.0` => `1.10.0`
* logger-f `1.9.0` => `1.10.0`

Close #93 - Upgrade sbt plugin and libraries

---

build.sbt
changelogs/0.5.0.md

* Upgrade sbt plugin and libraries (#93)
* sbt `1.4.9` => `1.5.1`
* sbt-devoops `2.1.0` => `2.3.0`
* http4s `0.21.20` => `0.21.22`
* cats-core `2.4.2` => `2.6.0`
* cats-effect `2.3.3` => `2.5.0`
* github4s `0.28.2` => `0.28.4`
* effectie `1.9.0` => `1.10.0`
* logger-f `1.9.0` => `1.10.0`
* Publish directly to Maven Central (#96)

sbt-github-pages v0.5.0

---

src/main/scala/githubpages/GitHubPagesKeys.scala
src/main/scala/githubpages/GitHubPagesPlugin.scala
website/docs/config.md

- Adapt code from [`sbt-ci-release`](https://github.com/olafurpg/sbt-ci-release/blob/3909fc9ef852940f726b1c1973d3cf56a24268e4/plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala#L109-L124) to retrieve organization/repository names from `git remote` information.
- Use previous extracted information to populate default values for `gitHubPagesOrgName`/`gitHubPagesRepoName`.
- Update documentation to reflect this change.

Add default values for org/repo names extracted from `git remote` info

---

changelogs/0.6.0.md

* Add default values for org/repo names extracted from `git remote` info (#102) - Thanks @alejandrohdezma

sbt-github-pages v0.6.0

---

build.sbt
project/plugins.sbt

- `cats` `2.6.0` => `2.6.1`
- `cats-effect` `2.5.0` => `2.5.3`
- `github4s` `0.28.4` => `0.28.5`
- `github4s` `0.28.4` => `0.28.5`
- `circe` `0.13.0` => `0.14.1`
- `http4s` `0.21.22` => `0.21.27`
- `effectie` `1.10.0` => `1.15.0`
- `logger-f` `1.10.0` => `1.15.0`
- `sbt-devoops` `2.6.0` => `2.10.0`

Close #106 - Upgraded libs and sbt plugins

---

changelogs/0.7.0.md

* Upgraded libs and sbt plugins (#106)
* `cats` `2.6.0` => `2.6.1`
* `cats-effect` `2.5.0` => `2.5.3`
* `github4s` `0.28.4` => `0.28.5`
* `github4s` `0.28.4` => `0.28.5`
* `circe` `0.13.0` => `0.14.1`
* `http4s` `0.21.22` => `0.21.27`
* `effectie` `1.10.0` => `1.15.0`
* `logger-f` `1.10.0` => `1.15.0`
* `sbt-devoops` `2.6.0` => `2.10.0`

sbt-github-pages v0.7.0

---

changelogs/0.8.0.md

* Add a link to the doc site to explain how to create publish branch (#114)

sbt-github-pages v0.8.0

---

changelogs/0.8.1.md

* `publishToGitHubPages` fails if you have greater than 30 branches alphabetically before `gh-pages` (#119) - Thanks @zarthross for the helpful bug report!

sbt-github-pages v0.8.1

---

changelogs/0.9.0.md

* Bump `effectie` and `logger-f` to `2.0.0-beta1` (#162)
* Upgrade libraries (#160)
* cats `2.6.1` => `2.7.0`
* cats-effect `2.5.3` => `3.3.5`
* github4s `0.28.5` => `0.31.0`
* http4s `0.21.27` => `0.23.11`
* ~~effectie `1.15.0` => `1.16.0`~~
* ~~logger-f `1.15.0` => `1.16.0`~~
* hedgehog `0.7.0` => `0.8.0`
* Publish to `s01.oss.sonatype.org` (the new Maven central) (#131)

sbt-github-pages v0.9.0

---

build.sbt
project/plugins.sbt

Upgrade: libraries and sbt plugins
- cats-effect `3.3.5` => `3.3.12`
- extras `0.13.0` => `0.14.0`
- sbt-docusaur `0.9.0` => `0.10.0`
- sbt-devoops `2.16.0` => `2.20.0`

Upgrade: libraries and sbt plugins

---

changelogs/0.10.0.md

* Add `settingKey` to set the request timeout for publishing GitHub Pages (#165)

sbt-github-pages v0.10.0

---

build.sbt
project/build.properties
project/plugins.sbt
src/main/scala/githubpages/GitHubPagesPlugin.scala
src/main/scala/githubpages/github/Data.scala
src/main/scala/githubpages/github/GitHubApi.scala

Close #171 - Upgrade Scala, sbt, sbt-plugins and libraries
* sbt 1.6.2 => 1.7.2
* Scala 2.12.12 => 2.12.17
* cats 2.7.0 => 2.8.0
* cats-effect 3.3.12 => 3.3.14
* github4s 0.31.0 => 0.31.2
* circe 0.14.1 => 0.14.3
* http4s 0.23.11 => 0.23.16
* http4s-blaze-client 0.23.12
* effectie 2.0.0-beta1 => 2.0.0-beta2
* logger-f 2.0.0-beta1 => 2.0.0-beta2
* extras 0.14.0 => 0.20.0

Close #171 - Upgrade Scala, sbt, sbt-plugins and libraries

---

changelogs/0.11.0.md

* Upgrade Scala, sbt, sbt-plugins and libraries (#171)
* sbt `1.6.2` => `1.7.2`
* Scala `2.12.12` => `2.12.17`
* cats `2.7.0` => `2.8.0`
* cats-effect `3.3.12` => `3.3.14`
* github4s `0.31.0` => `0.31.2`
* circe `0.14.1` => `0.14.3`
* http4s `0.23.11` => `0.23.16`
* http4s-blaze-client `0.23.12`
* effectie `2.0.0-beta1` => `2.0.0-beta2`
* logger-f `2.0.0-beta1` => `2.0.0-beta2`
* extras `0.14.0` => `0.20.0`

sbt-github-pages v0.11.0

---

changelogs/0.12.0.md

* Upgrade `effectie` and `logger-f` to `2.0.0-beta4` (#180) - and update the code accordingly / also upgrade other libraries
* effectie`2.0.0-beta2` => `2.0.0-beta4`
* logger-f`2.0.0-beta2` => `2.0.0-beta4`
* global sbt version`1.2.8` => `1.6.2`
* hedgehog`0.9.0` => `0.10.1`
* cats`2.8.0` => `2.9.0`
* cats-effect`3.3.14` => `3.4.3`
* http4s blaze client`0.23.12` => `0.23.13`
* extras`0.20.0` => `0.26.0`

sbt-github-pages v0.12.0

---

build.sbt
project/build.properties
project/plugins.sbt
src/main/scala/filef/FileError.scala

Close #200 - Upgrade Scala, sbt, sbt plugins and libraries
* Scala to `2.12.18`
* sbt to `1.9.7`
* sbt-ci-release to `1.5.12`
* sbt-wartremover to `3.1.5`
* sbt-devoops to `3.0.0`
* cats to `2.10.0`
* cats-effect to `3.5.2`
* github4s to `0.32.1`
* circe to `0.14.6`
* http4s to `0.23.24`
* http4s-blaze-client to `0.23.15`
* effectie to `2.0.0-beta13`
* logger-f to `2.0.0-beta22`
* extras to `0.44.0`

Close #200 - Upgrade Scala, sbt, sbt plugins and libraries

---

changelogs/0.13.0.md

* Upgrade Scala, sbt, sbt plugins and libraries (#200)
* Scala to `2.12.18`
* sbt to `1.9.7`
* sbt-ci-release to `1.5.12`
* sbt-wartremover to `3.1.5`
* sbt-devoops to `3.0.0`
* cats to `2.10.0`
* cats-effect to `3.5.2`
* github4s to `0.32.1`
* circe to `0.14.6`
* http4s to `0.23.24`
* http4s-blaze-client to `0.23.15`
* effectie to `2.0.0-beta13`
* logger-f to `2.0.0-beta22`
* extras to `0.44.0`

sbt-github-pages v0.13.0

---

build.sbt

Close #214 - Bump libraries
- cats-effect to 3.5.3
- http4s to 0.23.25
- http4s-blaze-client to 0.23.16
- effectie to 2.0.0-beta14
- logger-f to 2.0.0-beta24

Close #214 - Bump libraries

---

changelogs/0.14.0.md

* Allow force push (#213) - Thanks @michaelmior
* force push with the environment variable `GITHUB_PAGES_PUBLISH_FORCE_PUSH`
* Bump libraries (#214)
* cats-effect to `3.5.3`
* http4s to `0.23.25`
* http4s-blaze-client to `0.23.16`
* effectie to `2.0.0-beta14`
* logger-f to `2.0.0-beta24`
* Add `sbt-devoops-starter` (#216)
* Bump `sbt-devoops` to `3.1.0` (#218)

sbt-github-pages v0.14.0

---

.github/workflows/build.yml
.github/workflows/doc-site-build-only.yml
.github/workflows/doc-site-publish.yml
.github/workflows/release.yml

- Updated Java version to `11` and distribution to `temurin` in all workflows.
- Replaced `olafurpg/setup-scala` with `actions/setup-java` and `sbt/setup-sbt`.
- Added SBT cache configuration to `actions/setup-java`.
- Removed manual SBT cache steps.

Update GitHub Actions workflows

---

build.sbt
project/plugins.sbt
src/main/scala/githubpages/github/GitHubApi.scala

Update dependencies and refactor GitHub API usage
- Updated library versions in `build.sbt`:
- hedgehog to 0.12.0
- cats to 2.13.0
- cats-effect to 3.5.7
- github4s to 0.33.3
- circe to 0.14.12
- http4s to 0.23.30
- http4s-blaze-client to 0.23.17
- effectie to 2.0.0
- logger-f to 2.1.18
- Updated sbt-devoops version to 3.2.0 in `project/plugins.sbt`.
- Refactored `GitHubApi.scala` to use `GithubAPIs` instead of `Github`.

Close #234 - Bump libraries and sbt plugins

---

changelogs/0.15.0.md

* Bump libraries and sbt plugins (#234)
- Updated library versions in `build.sbt`:
- `hedgehog` to `0.12.0`
- `cats` to `2.13.0`
- `cats-effect` to `3.5.7`
- `github4s` to `0.33.3`
- `circe` to `0.14.12`
- `http4s` to `0.23.30`
- `http4s-blaze-client` to `0.23.17`
- `effectie` to `2.0.0`
- `logger-f` to `2.1.18`
- Updated `sbt-devoops` version to `3.2.0` in `project/plugins.sbt`.
- Refactored `GitHubApi.scala` to use `GithubAPIs` instead of `Github`.

sbt-github-pages v0.15.0
